import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import vm from 'node:vm'
const getMyInbox=async()=>({items:[],unread:0})
test('通知置顶读取本人真实数据，合并对话未读，点击打开办理记录且首页移除旧卡',async()=>{const paths=[],seen=[],{p,events,source}=await component('ConversationList',{getMyInbox:async(q,o)=>{seen.push(o.token);return {items:[{id:'notice',title:'人工复核通过'}],unread:4}},chatApi:async()=>({items:[{title:'群',unread:2}]}),openPage:path=>paths.push(path)});await p.load();assert.equal(p.inboxLatest.title,'人工复核通过');assert.equal(p.inboxUnread,4);assert.deepEqual(seen,['a']);assert.deepEqual(events.at(-1),['unread',6]);p.open('/pages/inbox/index');assert.deepEqual(paths,['/pages/inbox/index']);assert.ok(source.indexOf('class="conversation-inbox surface"')<source.indexOf('class="conversation-list surface"'));const home=await fs.readFile(new URL('../pages/home/index.vue',import.meta.url),'utf8');assert.doesNotMatch(home,/<view class="announcement-card/);assert.match(home,/class="notice-button"/)})
test('通知请求失败显示错误而不是伪造空列表，换号迟到数据不可泄露',async()=>{let token='a',resolve;const {p}=await component('ConversationList',{getAccessToken:()=>token,getMyInbox:()=>new Promise(r=>resolve=r)});p.sessionToken='a';const loading=p.loadInboxSummary(0,'a');token='b';p.generation++;p.reset('b');resolve({items:[{title:'甲的私密通知'}],unread:33});await loading;assert.equal(p.inboxLatest,null);assert.equal(p.inboxUnread,null);const {p:q}=await component('ConversationList',{getMyInbox:async()=>{throw new Error('网络中断')}});q.sessionToken='a';await q.loadInboxSummary(0,'a');assert.equal(q.inboxUnread,null);assert.equal(q.inboxError,'网络中断')})
test('未登录不请求通知；空列表如实显示；浮动红点包含通知未读',async()=>{let requests=0;const {p}=await component('ConversationList',{getAccessToken:()=>'',getMyInbox:async()=>{requests++}});await p.load();assert.equal(requests,0);const {p:q}=await component('ConversationList');await q.load();assert.equal(q.inboxUnread,0);assert.equal(q.inboxLatest,null);const {p:d}=await component('DesktopChatDock',{getMyInbox:async()=>({items:[],unread:7}),chatApi:async()=>({items:[{unread:3}]})});d.desktop=true;d.sessionToken='a';await d.checkUnread();assert.equal(d.unread,10)})

async function component(file,context={}){const source=await fs.readFile(new URL(`../components/${file}.vue`,import.meta.url),'utf8'),code=source.split('<script>')[1].split('</script>')[0].replace(/^import .*$/gm,'').replace('export default','globalThis.options=');const sandbox={isModuleEnabled:()=>true,enforceInitialPasswordChange:()=>false,getMyInbox:async()=>({items:[],unread:0}),ConversationList:{},ChatThread:{},chatApi:async()=>({items:[]}),getAccessToken:()=> 'a',conversationTitle:x=>x?.title||'对话',isFixedGroup:()=>false,canLeaveGroup:()=>false,canDissolveGroup:()=>false,chatUrl:x=>x,fileSize:x=>x,openPage(){},messageId:()=> 'id',setInterval:()=>1,clearInterval(){},AbortController,uni:{getStorageSync(){},setStorageSync(){},removeStorageSync(){},setTabBarBadge(){},removeTabBarBadge(){}},...context};vm.runInNewContext(code,sandbox);const o=sandbox.options,events=[],p={...o.data(),active:true,embedded:true,$refs:{},$nextTick:f=>f(),$emit:(...args)=>events.push(args)};for(const[name,fn]of Object.entries(o.methods||{}))p[name]=fn.bind(p);for(const[name,fn]of Object.entries(o.computed||{}))Object.defineProperty(p,name,{get:()=>fn.call(p)});return {p,o,events,source}}

test('关闭对话模块后不轮询不打开浮窗，已打开的会话被清除',async()=>{let calls=0;const {p,o}=await component('DesktopChatDock',{isModuleEnabled:()=>false,chatApi:async()=>{calls++;return{items:[]}}});p.desktop=true;p.sessionToken='a';await p.checkUnread();p.requestOpen({detail:{conversationId:'old'}});assert.equal(calls,0);assert.equal(p.opened,false);p.opened=true;p.everOpened=true;p.selectedId='old';o.watch.chatEnabled.call(p,false);assert.equal(p.opened,false);assert.equal(p.everOpened,false);assert.equal(p.selectedId,'')})
test('模块关闭时迟到未读和列表事件不能恢复旧内容，卸载立即停止定时器和监听',async()=>{let enabled=true,resolve,cleared=0;const removed=[],pending=new Promise(r=>resolve=r);const {p,o}=await component('DesktopChatDock',{isModuleEnabled:()=>enabled,chatApi:()=>pending,clearInterval:()=>cleared++,window:{removeEventListener:(event)=>removed.push(event)},document:{removeEventListener:(event)=>removed.push(event)},uni:{$off:event=>removed.push(event)}});p.desktop=true;p.sessionToken='a';p.query={removeEventListener:event=>removed.push(event)};const loading=p.checkUnread();enabled=false;p.select('stale-selection');assert.equal(p.selectedId,'');o.beforeUnmount.call(p);resolve({items:[{unread:99}]});await loading;assert.equal(p.unread,0);assert.equal(cleared,1);assert.deepEqual(removed,['change','hufe:open-desktop-chat','keydown','visibilitychange','hufe:auth-changed'])})
test('悬浮窗口关闭暂停组件，保留同一会话，不导航或嵌入iframe',async()=>{const {p,source}=await component('DesktopChatDock');p.desktop=true;p.sessionToken='a';p.requestOpen({detail:{conversationId:'conversation-one'}});assert.equal(p.opened,true);assert.equal(p.selectedId,'conversation-one');p.close();assert.equal(p.opened,false);assert.equal(p.working,false);p.toggle();assert.equal(p.selectedId,'conversation-one');assert.equal(p.working,true);assert.doesNotMatch(source,/<iframe/);assert.match(source,/:active="working"/);assert.match(source,/ChatThread/);assert.match(source,/ConversationList/)})
test('悬浮窗口换号销毁旧会话和列表，迟到的未读响应不回填',async()=>{let token='a',resolve;const pending=new Promise(r=>resolve=r);const {p}=await component('DesktopChatDock',{getAccessToken:()=>token,chatApi:(_path,options)=>options.token==='a'?pending:Promise.resolve({items:[]})});p.sessionToken='a';p.desktop=true;p.selectedId='private-a';p.everOpened=true;const read=p.checkUnread();token='b';p.authChanged();assert.equal(p.selectedId,'');assert.equal(p.everOpened,false);assert.equal(p.opened,false);resolve({items:[{unread:99}]});await read;assert.equal(p.sessionVersion,1);assert.equal(p.unread,0)})
test('共享私聊与建群使用嵌入事件，不切换底层页面；移动仍正常导航',async()=>{const paths=[],{p,events}=await component('ConversationList',{openPage:path=>paths.push(path)});p.open('/pages/chat/index?id=test-one');assert.deepEqual(events,[['conversation','test-one']]);assert.equal(paths.length,0);p.embedded=false;p.open('/pages/chat/index?id=test-two');assert.deepEqual(paths,['/pages/chat/index?id=test-two'])})
test('会话组件切换id清空旧内容，收起后停止轮询并暂停附件，重新打开保留草稿',async()=>{let ticks=0;const {p,o}=await component('ChatThread',{setInterval:()=>++ticks});p.id='first';p.sessionToken='a';p.draft='未发文字';p.refresh=()=>{};p.activate();assert.equal(ticks,1);p.stop();assert.equal(p.draft,'未发文字');p.activate();assert.equal(p.draft,'未发文字');o.watch.conversationId.call(p,'second');assert.equal(p.id,'second');assert.equal(p.draft,'');assert.equal(p.conversation,null);assert.equal(p.messages.length,0);p.active=false;const before=ticks;p.activate();assert.equal(ticks,before)})
test('桌面入口按真实tab标签标记，不依赖错误子节点序号；手机保留原tab及会话路由',async()=>{const app=await fs.readFile(new URL('../App.vue',import.meta.url),'utf8'),mount=await fs.readFile(new URL('../utils/desktopChatMount.js',import.meta.url),'utf8'),helper=await fs.readFile(new URL('../utils/desktopChat.js',import.meta.url),'utf8');assert.match(app,/\.uni-tabbar__item\[data-hufe-chat-tab\]/);assert.doesNotMatch(app,/\.uni-tabbar__item:nth-child\(3\)/);assert.match(mount,/textContent.trim\(\)==='对话'/);assert.match(helper,/min-width: 1024px/);assert.match(helper,/pointer: fine/);for(const file of ['chat','conversations']){const source=await fs.readFile(new URL(`../pages/${file}/index.vue`,import.meta.url),'utf8');assert.match(source,/v-if="!desktop"/);assert.match(source,/screenQuery.*removeEventListener/)}})
