import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import vm from 'node:vm'
import {webcrypto} from 'node:crypto'
import {isRevokedSession,sessionEndMessage} from '../utils/sessionErrors.js'
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)||'',setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}}
async function evaluate(file,context,expose){const code=(await fs.readFile(new URL('../'+file,import.meta.url),'utf8')).replace(/^import[\s\S]*?from\s+['"][^'"]+['"];?\r?\n/gm,'').replace(/import\.meta\.env\?\.VITE_API_BASE_URL/g,"'/api/v1'").replace(/^export /gm,'');vm.runInNewContext(code+'\nObject.assign(globalThis,{'+expose.join(',')+'})',context);return context}
test('随机设备ID在同源前后台与重启后相同，不读取UA/IP，独立存储拥有独立ID',async()=>{const local=storage();const a=await evaluate('utils/deviceIdentity.js',{window:{localStorage:local},crypto:webcrypto},['getDeviceId']);const b=await evaluate('utils/deviceIdentity.js',{window:{localStorage:local},crypto:webcrypto},['getDeviceId']);assert.match(a.getDeviceId(),/^device_[0-9a-f]{32}$/);assert.equal(a.getDeviceId(),b.getDeviceId());const c=await evaluate('utils/deviceIdentity.js',{window:{localStorage:storage()},crypto:webcrypto},['getDeviceId']);assert.notEqual(a.getDeviceId(),c.getDeviceId())})
test('后台持久token迁移旧sessionStorage，浏览器重启复用；网络和普通密码错误不强退',async()=>{const local=storage(),legacy=storage();legacy.setItem('hufe.admin.access-token','old-token');let result={ok:false,status:500,json:async()=>({code:'INTERNAL_ERROR',message:'服务器暂不可用'})},expired=0;const args=()=>({URL,Headers,CustomEvent:class{},localStorage:local,sessionStorage:legacy,isRevokedSession,sessionEndMessage,window:{location:{origin:'http://localhost:4180'},dispatchEvent:()=>expired++},fetch:async()=>result});const a=await evaluate('admin/src/lib/api.js',args(),['api','accessToken','saveAccessToken']);assert.equal(a.accessToken(),'old-token');assert.equal(legacy.getItem('hufe.admin.access-token'),'');const b=await evaluate('admin/src/lib/api.js',args(),['api','accessToken']);assert.equal(b.accessToken(),'old-token');await assert.rejects(b.api('/me'));assert.equal(b.accessToken(),'old-token');result={ok:false,status:401,json:async()=>({code:'CURRENT_PASSWORD_INVALID',message:'当前密码错误'})};await assert.rejects(b.api('/auth/change-password'));assert.equal(b.accessToken(),'old-token');assert.equal(expired,0);result={ok:false,status:401,json:async()=>({code:'SESSION_REPLACED',message:'其他设备已登录'})};await assert.rejects(b.api('/me'));assert.equal(b.accessToken(),'');assert.equal(expired,1)})
async function adminAuth(overrides={}){let token='a';const listeners={};const context={computed:f=>({get value(){return f()}}),reactive:x=>x,getDeviceId:()=> 'device_12345678901234567890123456789012',isRevokedSession,accessToken:()=>token,saveAccessToken:t=>token=t,api:async()=>({id:'a',isAdmin:true,isSuperAdmin:true}),window:{addEventListener:(name,fn)=>listeners[name]=fn},...overrides};await evaluate('admin/src/lib/auth.js',context,['auth']);return {...context,getToken:()=>token,setToken:t=>token=t,listeners}}
test('后台启动网络失败保留凭证，恢复后重查真实用户；并发刷新只发一次',async()=>{let calls=0;const wait=deferred();const a=await adminAuth({api:async()=>{calls++;if(calls===1)throw new Error('offline');return wait.promise}});await a.auth.bootstrap();assert.equal(a.getToken(),'a');assert.equal(a.auth.state.user,null);assert.match(a.auth.state.sessionError,/未被清除/);const p=a.auth.bootstrap(true),q=a.auth.bootstrap(true);assert.equal(calls,2);wait.resolve({id:'a',isAdmin:true});await Promise.all([p,q]);assert.equal(a.auth.state.user.id,'a');assert.equal(a.auth.state.sessionError,'')})
test('后台换号后迟到/me不能覆盖新用户，退出中迟到结果不能清除后来登录',async()=>{const stale=deferred();const a=await adminAuth({api:async(path)=>path==='/me'?stale.promise:path==='/auth/login'?{accessToken:'b',user:{id:'b',isAdmin:true}}:{}});const boot=a.auth.bootstrap();await a.auth.login('b','not-stored');stale.resolve({id:'a',isAdmin:true});await boot;assert.equal(a.getToken(),'b');assert.equal(a.auth.state.user.id,'b');const pending=deferred();const b=await adminAuth({api:async(path)=>path==='/auth/logout'?pending.promise:{accessToken:'c',user:{id:'c',isAdmin:true}}});const logout=b.auth.logout();assert.equal(b.getToken(),'');await b.auth.login('c','not-stored');pending.resolve({});await logout;assert.equal(b.getToken(),'c');assert.equal(b.auth.state.user.id,'c')})
test('前台持久会话允许null有效期，并发资料刷新只读一次；断网不清、替换明确退出',async()=>{let auth={accessToken:'a',expiresAt:null},calls=0,cleared=0,lastUser=null;const pending=deferred();const c={isRevokedSession,sessionEndMessage,readAuthState:()=>auth,updateAuthenticatedUser:u=>lastUser=u,request:async()=>{calls++;return pending.promise},invalidateAuthenticatedSession:(token)=>{if(auth.accessToken===token){auth={accessToken:''};cleared++}},uni:{$emit(){}},ApiError:Error};await evaluate('services/schoolAuth.js',c,['refreshPlatformProfile']);const first=c.refreshPlatformProfile(),second=c.refreshPlatformProfile();assert.equal(calls,1);pending.resolve({id:'a'});await Promise.all([first,second]);assert.equal(lastUser.id,'a');assert.equal(auth.accessToken,'a');c.request=async()=>{throw Object.assign(Error('offline'),{code:'NETWORK_ERROR'})};await assert.rejects(c.refreshPlatformProfile());assert.equal(cleared,0);c.request=async()=>{throw Object.assign(Error('elsewhere'),{code:'SESSION_REPLACED'})};await c.refreshPlatformProfile();assert.equal(cleared,1);assert.equal(auth.accessToken,'')})
test('前台两个登录响应倒序到达只接受最后一次，显式退出不会被旧登录复活',async()=>{const first=deferred();let auth={accessToken:''},calls=0;const c={readAuthState:()=>auth,getDeviceId:()=> 'device_12345678901234567890123456789012',saveAuthenticatedSession:x=>auth=x,clearAuthState:()=>auth={accessToken:''},uni:{$emit(){}},ApiError:Error,request:async({path,data})=>{if(path.endsWith('/logout'))return {};calls++;return data.username==='a'?first.promise:{accessToken:'b',user:{id:'b'}}}};await evaluate('services/schoolAuth.js',c,['loginPlatformAccount','logoutPlatformAccount']);const a=c.loginPlatformAccount({username:'a',password:'one'});await c.loginPlatformAccount({username:'b',password:'two'});first.resolve({accessToken:'a',user:{id:'a'}});await assert.rejects(a,/后续操作/);assert.equal(auth.accessToken,'b');assert.equal(calls,2);const pending=deferred();c.request=async({path})=>path.endsWith('/logout')?{}:pending.promise;const older=c.loginPlatformAccount({username:'a',password:'one'});await c.logoutPlatformAccount();pending.resolve({accessToken:'a',user:{id:'a'}});await assert.rejects(older);assert.equal(auth.accessToken,'')})
