import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import {createHash} from 'node:crypto'
import {JsonDatabase} from '../src/storage/json-database.js'
import {EnterpriseLookupService} from '../src/enterprise-lookup/service.js'
import {RegionService} from '../src/regions/service.js'
async function setup(t,fetcher){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hufe-enterprise-lookup-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const db=await new JsonDatabase(path.join(dir,'data.json')).init();await db.transaction(s=>{s.accounts=[{id:'admin',isAdmin:true,status:'active'},{id:'user',schoolIdentityVerified:true,status:'active'},{id:'other',schoolIdentityVerified:true,status:'active'},{id:'guest',status:'active'},{id:'delegated',isAdmin:true,role:'delegated_admin',status:'active'}]});const config={dataHashSecret:'test-only-enterprise-secret',dataFile:db.file};return {db,service:new EnterpriseLookupService(db,config,await new RegionService(db,config).init(),{fetcher})}}
const settings={revision:0,enabled:true,dailyLimit:3,appKey:'test-appkey-only',secretKey:'test-secret-only',licensed:true}
test('企业登记地区不会回填已停用的区域或其子级',async t=>{const {service}=await setup(t);const c=service.regions.current();service.regions.current=()=>({...c,active:()=>false});assert.deepEqual(service.region({AreaCode:'430104',Area:{Province:'湖南省',City:'长沙市'}}),{city:'',regionCode:''})})
const payload={Status:'200',Result:{Name:'隔离测试有限责任公司',CreditCode:'9111010859963405XW',Industry:{Industry:'信息传输、软件和信息技术服务业'},Area:{Province:'湖南省',City:'长沙市'},AreaCode:'430104',Scope:'软件开发与测试服务，仅为自动化测试数据。',Address:'测试登记地址',ContactInfo:{Email:'test@example.invalid'},Employees:[{Name:'不得泄露的员工名单'}]}}
test('查询默认不开启，只有全局管理员可配置；密钥加密和日志不泄密，版本冲突保护',async t=>{const {service,db}=await setup(t);assert.equal((await service.lookup('user','隔离测试有限责任公司')).available,false);assert.throws(()=>service.status('user'));assert.throws(()=>service.status('delegated'));await assert.rejects(service.save('admin',{...settings,licensed:false}));await service.save('admin',settings);const state=service.status('admin');assert.equal(state.configured,true);assert.doesNotMatch(JSON.stringify(db.read()),/test-secret-only|test-appkey-only/);assert.doesNotMatch(JSON.stringify(state),/credentials|secretKey/);await assert.rejects(service.save('admin',settings),{code:'REVISION_CONFLICT'});await assert.rejects(service.save('admin',{...settings,revision:1,endpoint:'http://127.0.0.1'}));await assert.rejects(service.lookup('guest','隔离测试有限责任公司'))})
test('固定官方地址和签名、白名单回填、城市库匹配；同名并发请求只花一次额度',async t=>{let calls=0;const {service}=await setup(t,async(url,options)=>{calls++;assert.equal(url.origin,'https://api.qichacha.com');assert.equal(url.pathname,'/ECIInfoVerify/GetInfo');assert.equal(options.redirect,'error');assert.equal(options.headers.Token,createHash('md5').update(settings.appKey+options.headers.Timespan+settings.secretKey).digest('hex').toUpperCase());return new Response(JSON.stringify(payload))});await service.save('admin',settings);const [a,b]=await Promise.all([service.lookup('user',payload.Result.Name),service.lookup('other',payload.Result.Name)]);assert.equal(calls,1);assert.equal(a.available,true);assert.equal(a.fields.regionCode,'CN-430104');assert.equal(a.fields.city,'长沙市');assert.equal(a.fields.creditCode,payload.Result.CreditCode);assert.deepEqual(a,b);assert.doesNotMatch(JSON.stringify(a),/Employees|不得泄露|contactName|ownerId|verified/);await service.lookup('user',payload.Result.Name);assert.equal(calls,1);assert.equal(service.status('admin').usedToday,1)})
test('服务错误或不完全匹配不捏造结果，每日额度生效，关闭立即生效',async t=>{let calls=0;const {service}=await setup(t,async()=>{calls++;return new Response(JSON.stringify({...payload,Result:{...payload.Result,Name:'其他公司'}}))});await service.save('admin',{...settings,dailyLimit:1});assert.equal((await service.lookup('user',payload.Result.Name)).available,false);await assert.rejects(service.lookup('user','另一家隔离测试公司'),{code:'ENTERPRISE_LOOKUP_QUOTA'});assert.equal(calls,1);await service.save('admin',{revision:1,enabled:false,dailyLimit:1});assert.equal((await service.lookup('user',payload.Result.Name)).available,false)})
test('上游超大/异常响应不透传，查询途中撤销用户或停用服务拒绝迟到响应',async t=>{const {service,db}=await setup(t,async()=>new Response('not json'));await service.save('admin',settings);await assert.rejects(service.lookup('user',payload.Result.Name),{code:'ENTERPRISE_LOOKUP_UNAVAILABLE'});let resolve;service.fetcher=()=>new Promise(r=>{resolve=r});const pending=service.lookup('user','新的隔离测试公司');while(!resolve)await new Promise(r=>setTimeout(r,1));await db.transaction(s=>{s.accounts.find(a=>a.id==='user').status='suspended'});resolve(new Response(JSON.stringify({...payload,Result:{...payload.Result,Name:'新的隔离测试公司'}})));await assert.rejects(pending,{code:'ACCOUNT_REQUIRED'})})
