import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import {JsonDatabase} from '../src/storage/json-database.js'
import {RegionService,validateRegions} from '../src/regions/service.js'
import {updateSelfProfile} from '../src/accounts/profile.js'
const admin={id:'qa-admin'}
const guard=d=>{if(!d.accounts.some(a=>a.id===admin.id&&a.isAdmin))throw Error('forbidden')}
async function setup(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'hufe-regions-'));const config={dataFile:path.join(dir,'data.json')};const db=await new JsonDatabase(config.dataFile).init();await db.transaction(d=>{d.accounts.push({id:admin.id,isAdmin:true,status:'active'},{id:'person',status:'active',personalProfile:{city:'历史城市'}})});const regions=await new RegionService(db,config).init();const original=regions.preview.bind(regions);regions.preview=(admin,input)=>original(admin,{expectedRevision:regions.meta().revision,...input});t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {db,regions,config}}
test('真实底库覆盖国家到乡镇，直筒子市不丢街道，父级按需加载',async t=>{const {regions}=await setup(t);assert.equal(regions.stats().total,53877);const changsha=regions.describe('CN-4301');assert.equal(changsha.name,'长沙市');assert.deepEqual(changsha.path.map(r=>r.code),['CN','CN-43','CN-4301']);assert.equal(regions.list({parentCode:'CN-43'}).items.some(r=>r.code==='CN-4301'),true);for(const code of ['4419','4420','4604','6202'])assert.ok(regions.list({parentCode:'CN-'+code}).items.some(r=>r.level==='street'));assert.ok(regions.list({query:'长沙'}).items.length);assert.equal(regions.selection({city:'伪造地区',regionCode:'CN-4301'}).city,'长沙市')})
test('导入预览无写入、版本冲突、跨账号拒绝、重复确认和停用祖先',async t=>{const {db,regions,config}=await setup(t);const row={...regions.current().byCode.get('CN-43'),enabled:false};const input={source:'测试授权维护',sourceVersion:'test-1',mode:'merge',items:[row]};const p=regions.preview(admin,input);assert.equal(regions.describe('CN-4301').available,true);await assert.rejects(()=>regions.apply({id:'other'},p.token,{},guard));await regions.apply(admin,p.token,{actor:admin.id},guard);assert.equal(regions.describe('CN-4301').available,false);assert.equal(regions.list({parentCode:'CN-43'}).items.length,0);assert.throws(()=>regions.selection({regionCode:'CN-4301',city:'长沙市'}));assert.equal(regions.selection({regionCode:'CN-4301',city:'长沙市'},{regionCode:'CN-4301',city:'长沙市'}).city,'长沙市');await assert.rejects(()=>regions.apply(admin,p.token,{},guard));assert.equal((await new RegionService(db,config).init()).describe('CN-4301').available,false);const a=regions.preview(admin,{...input,items:[{...row,enabled:true}]}),b=regions.preview({id:'other'},{...input,items:[{...row,enabled:true}]});await regions.apply(admin,a.token,{},guard);await assert.rejects(()=>regions.apply({id:'other'},b.token,{},()=>{}),e=>e.code==='REGION_CONFLICT');assert.ok(db.read(d=>d.auditLogs.some(r=>r.action==='regions.updated')))})
test('无效导入整批拒绝；磁盘失败不发布新版本',async t=>{const {db,regions}=await setup(t);for(const items of [[{code:'X',parentCode:'missing',name:'错误',level:'city',enabled:true}],[{code:'CN',parentCode:'',name:'中国',level:'country',enabled:true},{code:'CN',parentCode:'',name:'重复',level:'country',enabled:true}]])assert.throws(()=>regions.preview(admin,{source:'测试',sourceVersion:'1',mode:'merge',items}));assert.throws(()=>validateRegions([{code:'A',parentCode:'B',name:'甲',level:'city',enabled:true},{code:'B',parentCode:'A',name:'乙',level:'province',enabled:true}]));const row=regions.current().byCode.get('CN-43');const p=regions.preview(admin,{source:'测试',sourceVersion:'2',mode:'merge',items:[{...row,name:'修改名称'}]});const persist=db.persist;db.persist=async()=>{throw Error('disk full')};await assert.rejects(()=>regions.apply(admin,p.token,{},guard));db.persist=persist;assert.equal(regions.meta().revision,0);assert.equal(regions.describe('CN-43').name,'湖南省')})
test('资料城市不能任填；旧城市原样保留，精确地区仅本人资料存储',async t=>{const {db,regions}=await setup(t);await updateSelfProfile(db,'person',{revision:0,fields:{city:'历史城市',bio:'简介'}},{},regions);await assert.rejects(()=>updateSelfProfile(db,'person',{revision:1,fields:{city:'随意文字'}},{},regions),e=>e.code==='REGION_SELECTION_REQUIRED');const p=await updateSelfProfile(db,'person',{revision:1,fields:{city:'假的名称',regionCode:'CN-4301'}},{},regions);assert.equal(p.fields.city,'长沙市');assert.equal(p.fields.regionCode,'CN-4301');assert.equal(db.read(d=>d.accounts.find(a=>a.id==='person').city),undefined);await assert.rejects(()=>updateSelfProfile(db,'person',{revision:2,fields:{city:'线上',regionCode:'REMOTE'}},{},regions));assert.equal(regions.selection({city:'线上',regionCode:'REMOTE'},{},true).city,'线上 / 远程')})
