<script setup>
import {ref,watch,onBeforeUnmount} from 'vue'
import {api} from '../lib/api.js'
const props=defineProps({modelValue:{type:String,default:''},code:{type:String,default:''},allowRemote:Boolean,disabled:Boolean,id:String})
const emit=defineEmits(['update:modelValue','update:code'])
const open=ref(false),trail=ref([]),items=ref([]),query=ref(''),error=ref(''),loading=ref(false),page=ref(1),hasMore=ref(false),label=ref('');let generation=0
function close(){open.value=false;generation++;loading.value=false}
async function load(append=false){const version=++generation;loading.value=true;error.value='';try{const r=await api('/regions?'+new URLSearchParams({parentCode:trail.value.at(-1)?.code||'',query:query.value,page:page.value}),{token:''});if(version!==generation)return;items.value=append?[...items.value,...r.items]:r.items;hasMore.value=r.hasMore}catch(e){if(version===generation)error.value=e.message}finally{if(version===generation)loading.value=false}}
async function begin(){open.value=true;trail.value=[];query.value='';page.value=1;const version=++generation;if(props.code&&props.code!=='REMOTE'){try{const r=await api('/regions/'+encodeURIComponent(props.code),{token:''});if(version!==generation)return;if(r.available)trail.value=r.path}catch{}}if(version===generation)load()}
function choose(r){trail.value=r.path;query.value='';page.value=1;load()}
function back(i){trail.value=trail.value.slice(0,i+1);query.value='';page.value=1;load()}
async function confirm(){const version=++generation;loading.value=true;try{const r=await api('/regions/'+encodeURIComponent(trail.value.at(-1).code),{token:''});if(version!==generation)return;if(!r.available)throw Error('该地区已停用，请重新选择');emit('update:modelValue',r.city);emit('update:code',r.code);label.value=r.label;close()}catch(e){if(version===generation)error.value=e.message}finally{if(version===generation)loading.value=false}}
function clear(){emit('update:modelValue','');emit('update:code','');label.value='';close()}
function remote(){emit('update:modelValue','线上 / 远程');emit('update:code','REMOTE');label.value='线上 / 远程';close()}
watch(()=>props.code,async code=>{label.value='';if(code&&code!=='REMOTE'){try{const r=await api('/regions/'+encodeURIComponent(code),{token:''});if(code===props.code)label.value=r.label+(r.available?'':'（已停用）')}catch{}}},{immediate:true})
onBeforeUnmount(close)
</script>
<template><div class="region-select"><button :id="id" class="region-select-trigger" type="button" :disabled="disabled" @click="begin">{{ label || modelValue || '请选择国家/地区及城市' }} <span>选择 ›</span></button><div v-if="open" class="region-select-panel"><header><strong>选择地区</strong><button type="button" @click="close">关闭</button></header><p>可停留在任意已有层级，详细门牌地址另行填写。</p><nav><button type="button" @click="back(-1)">国家/地区</button><button v-for="(r,i) in trail" :key="r.code" type="button" @click="back(i)">{{ r.name }} ›</button></nav><div class="region-select-search"><input v-model="query" aria-label="搜索地区" placeholder="搜索地区名称或代码" @keydown.enter.prevent="page=1;load()"/><button type="button" @click="page=1;load()">搜索</button></div><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">加载中…</p><div v-else class="region-select-options"><button v-for="r in items" :key="r.code" type="button" @click="choose(r)"><strong>{{ r.name }}</strong><small>{{ query?r.label:(r.hasChildren?'下一级 ›':'选择') }}</small></button><p v-if="!items.length">没有下级或匹配地区，可使用当前地区。</p><button v-if="hasMore" type="button" @click="page++;load(true)">加载更多</button></div><footer><button type="button" @click="clear">清空</button><button v-if="allowRemote" type="button" @click="remote">线上 / 远程</button><button type="button" :disabled="!trail.length||loading||!!error" @click="confirm">使用此地区</button></footer></div></div></template>
<style scoped>
.region-select{min-width:0}.region-select button{font:inherit;font-size:14px;padding:9px 12px;color:#123963;background:#f7f9fd;border:1px solid #d8e1ed;border-radius:8px;cursor:pointer}.region-select-trigger{display:flex;justify-content:space-between;gap:14px;width:100%;text-align:left;overflow-wrap:anywhere;min-height:44px}.region-select-trigger span{flex-shrink:0}.region-select-panel{margin:10px 0;padding:15px;border:1px solid #cad8e9;border-radius:12px;background:white}.region-select-panel header,.region-select-panel footer,.region-select-search{display:flex;gap:8px;align-items:center;justify-content:space-between}.region-select-panel p{font-size:13px;line-height:1.6;color:#6b7d94}.region-select-panel nav{display:flex;flex-wrap:wrap;gap:5px;margin:12px 0}.region-select-search input{min-width:0;flex:1}.region-select-options{max-height:240px;overflow:auto;margin:12px 0}.region-select-options>button{display:flex;width:100%;justify-content:space-between;gap:12px;text-align:left;background:white;border:0;border-bottom:1px solid #edf0f4;border-radius:0;min-height:42px}.region-select-options small{max-width:65%;color:#70839b;overflow-wrap:anywhere}.region-select footer{justify-content:flex-end;flex-wrap:wrap}.region-select button:disabled{opacity:.5;cursor:default}
</style>
