import { ChatAdminService } from './admin-service.js'
const data = value => ({code:0,message:'ok',data:value})
export async function chatRoutes(app,{chat,requireUser,requireSuperAdmin}){
  const oversight = new ChatAdminService(chat)
  app.get('/api/v1/admin/chat/conversations',r=>{requireSuperAdmin(r);return data(oversight.list(r.user.id,r.query))})
  app.get('/api/v1/admin/chat/conversations/:id/messages',r=>{requireSuperAdmin(r);return data(oversight.detail(r.user.id,r.params.id,r.query))})
  app.patch('/api/v1/admin/chat/conversations/:id',async r=>{requireSuperAdmin(r);return data(await oversight.moderate(r.user.id,r.params.id,null,r.body||{},r.auditTrace))})
  app.put('/api/v1/admin/chat/conversations/:id/owner',async r=>{requireSuperAdmin(r);return data(await chat.assignOwner(r.user.id,r.params.id,r.body||{},r.auditTrace))})
  app.patch('/api/v1/admin/chat/conversations/:id/messages/:messageId',async r=>{requireSuperAdmin(r);return data(await oversight.moderate(r.user.id,r.params.id,r.params.messageId,r.body||{},r.auditTrace))})
  app.post('/api/v1/admin/chat/files/:id/ticket',r=>{requireSuperAdmin(r);const authorization=r.headers.authorization;return data(chat.ticket(r.user.id,r.params.id,{admin:true,authorize:()=>requireSuperAdmin({headers:{authorization}})}))})
  app.addHook('onRoute',options=>{const existing=options.config?.rateLimit||{};options.config={...options.config,rateLimit:{max:600,timeWindow:'1 minute',...existing,keyGenerator:request=>request.user?.id||request.ip}}})
  app.addContentTypeParser('application/octet-stream',{parseAs:'buffer',bodyLimit:chat.chunkSize},(_r,body,done)=>done(null,body))
  let chunksInFlight=0
  app.addHook('onRequest',async(request,reply)=>{reply.header('cache-control','private, no-store');const route=request.routeOptions.url;const publicRead=['GET','HEAD'].includes(request.method)&&['/api/v1/chat/files/:id','/api/v1/chat/stickers/:id/content'].includes(route);if(!publicRead){requireUser(request);await chat.syncSchoolGroups()}if(route==='/api/v1/chat/uploads/:id/chunks/:index'){if(chunksInFlight>=4)throw Object.assign(new Error('上传繁忙，请稍后重试'),{code:'CHAT_BUSY',statusCode:429});chunksInFlight++;request.chatChunkReserved=true}})
  const releaseChunk = request => { clearTimeout(request.chatChunkTimeout);if(request.chatChunkReserved){chunksInFlight--;request.chatChunkReserved=false} }
  app.addHook('onRequest',async (request,reply)=>{if(request.chatChunkReserved){request.raw.once('aborted',()=>releaseChunk(request));reply.raw.once('close',()=>releaseChunk(request));request.chatChunkTimeout=setTimeout(()=>{releaseChunk(request);request.raw.destroy()},120000);request.chatChunkTimeout.unref()}})
  app.addHook('onTimeout',async request=>releaseChunk(request))
  app.addHook('onSend',async(request,reply,payload)=>{if(['/api/v1/chat/files/:id','/api/v1/chat/stickers/:id/content'].includes(request.routeOptions.url))reply.header('Cross-Origin-Resource-Policy','cross-origin');return payload})
  app.addHook('onResponse',async request=>releaseChunk(request))
  app.get('/api/v1/chat/people',r=>data({items:chat.people(r.user.id,r.query.query)}))
  app.get('/api/v1/chat/conversations',r=>data(chat.list(r.user.id)))
  app.post('/api/v1/chat/conversations',{config:{rateLimit:{max:20,timeWindow:'1 minute'}}},async(r,p)=>{p.code(201);return data(await chat.create(r.user.id,r.body||{}))})
  app.get('/api/v1/chat/conversations/:id',r=>data(chat.conversation(r.user.id,r.params.id)))
  app.patch('/api/v1/chat/conversations/:id',async r=>data(await chat.group(r.user.id,r.params.id,r.body||{},r.auditTrace)))
  app.post('/api/v1/chat/conversations/:id/leave',async r=>data(await chat.leave(r.user.id,r.params.id,r.auditTrace)))
  app.post('/api/v1/chat/conversations/:id/dissolve',{bodyLimit:4096,config:{rateLimit:{max:20,timeWindow:'1 minute'}}},async r=>data(await chat.dissolve(r.user.id,r.params.id,r.body||{},r.auditTrace)))
  app.get('/api/v1/chat/conversations/:id/messages',r=>data(chat.messages(r.user.id,r.params.id,r.query)))
  app.post('/api/v1/chat/conversations/:id/messages',{config:{rateLimit:{max:60,timeWindow:'1 minute'}}},async(r,p)=>{p.code(201);const m=await chat.send(r.user.id,r.params.id,r.body||{},r.auditTrace);r.auditTargetIds=[m.id];return data(m)})
  app.post('/api/v1/chat/conversations/:id/read',async r=>data(await chat.read(r.user.id,r.params.id,r.body?.seq)))
  app.post('/api/v1/chat/conversations/:id/uploads',async(r,p)=>{p.code(201);return data(await chat.startUpload(r.user.id,r.params.id,r.body||{}))})
  app.get('/api/v1/chat/uploads/:id',async r=>data(await chat.uploadStatus(r.user.id,r.params.id)))
  app.put('/api/v1/chat/uploads/:id/chunks/:index',{bodyLimit:chat.chunkSize,config:{rateLimit:{max:2000,timeWindow:'1 minute'}},onRequest:async r=>{chat.ownedUpload(r.user.id,r.params.id)}},async r=>data(await chat.putChunk(r.user.id,r.params.id,Number(r.params.index),r.body)))
  app.post('/api/v1/chat/uploads/:id/complete',async r=>data(await chat.complete(r.user.id,r.params.id)))
  app.delete('/api/v1/chat/uploads/:id',async r=>data(await chat.cancel(r.user.id,r.params.id)))
  app.post('/api/v1/chat/files/:id/ticket',r=>data(chat.ticket(r.user.id,r.params.id)))
  app.get('/api/v1/chat/files/:id',(r,p)=>{const f=chat.download(r.params.id,r.query.ticket,r.headers.range);r.user=f.admin?chat.admin(f.actorId):chat.account(f.actorId);r.auditTicketScope=f.admin?'admin-chat-ticket':'member-chat-ticket';p.code(f.status).type(f.u.mimeType).header('Content-Length',f.end-f.start+1).header('Accept-Ranges','bytes').header('X-Content-Type-Options','nosniff').header('Referrer-Policy','no-referrer').header('Content-Security-Policy',"default-src 'none'; sandbox").header('Content-Disposition',`${f.u.mimeType.startsWith('image/')?'inline':'attachment'}; filename="download"; filename*=UTF-8''${encodeURIComponent(f.u.name)}`);if(f.status===206)p.header('Content-Range',`bytes ${f.start}-${f.end}/${f.u.size}`);return p.send(f.stream)})
  app.get('/api/v1/chat/stickers',r=>data(chat.stickers(r.user.id)))
  app.get('/api/v1/chat/stickers/:id/content',async(r,p)=>{const s=await chat.stickerContent(r.params.id);return p.type(s.mimeType).header('X-Content-Type-Options','nosniff').send(s.bytes)})
  app.get('/api/v1/admin/chat/stickers/:id/content',async(r,p)=>{requireSuperAdmin(r);const s=await chat.stickerContent(r.params.id,r.user.id);return p.type(s.mimeType).header('X-Content-Type-Options','nosniff').send(s.bytes)})
  app.get('/api/v1/admin/chat-stickers',r=>{requireSuperAdmin(r);return data(chat.stickers(r.user.id,true))})
  app.post('/api/v1/admin/chat-stickers',{bodyLimit:3*1024*1024},async r=>{requireSuperAdmin(r);return data(await chat.saveSticker(r.user.id,r.body||{}))})
  app.put('/api/v1/admin/chat-stickers/:id',{bodyLimit:3*1024*1024},async r=>{requireSuperAdmin(r);return data(await chat.saveSticker(r.user.id,r.body||{},r.params.id))})
}
