import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto'
import {auditRecord} from '../audit/metadata.js'

const endpoint='https://api.qichacha.com/ECIInfoVerify/GetInfo'
const fail=(message,code='ENTERPRISE_LOOKUP_INVALID',statusCode=400)=>Object.assign(new Error(message),{code,statusCode})
const clean=(value,max=160)=>typeof value==='string'?value.replace(/[\u0000-\u001f<>]/g,'').trim().slice(0,max):''
const canonical=value=>clean(value).normalize('NFKC').replace(/\s/g,'')
export class EnterpriseLookupService {
  constructor(database,config,regions,{fetcher=fetch}={}){this.db=database;this.regions=regions;this.fetcher=fetcher;this.cache=new Map();this.pending=new Map();this.key=createHash('sha256').update('hufe-enterprise-lookup:'+config.dataHashSecret).digest()}
  account(id,admin=false,state){const a=(state||this.db.read()).accounts.find(a=>a.id===id);if(!a||a.status!=='active'||a.mustChangePassword)throw fail('请使用可用账号登录并完成密码设置','ACCOUNT_REQUIRED',403);if(admin?(!a.isAdmin||[a.role,a.adminRole].includes('delegated_admin')):(!a.schoolIdentityVerified||a.developmentSchoolIdentityFixture||a.localDevelopmentOnly))throw fail(admin?'仅全局管理员可配置企业查询':'仅正式实名用户可查询企业资料','ENTERPRISE_LOOKUP_FORBIDDEN',403);return a}
  seal(value){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',this.key,iv);c.setAAD(Buffer.from('enterprise-lookup'));const b=Buffer.concat([c.update(JSON.stringify(value)),c.final()]);return [iv,c.getAuthTag(),b].map(v=>v.toString('base64url')).join('.')}
  secrets(row){if(!row?.credentials)return {};try{const [iv,tag,b]=row.credentials.split('.').map(v=>Buffer.from(v,'base64url')),d=createDecipheriv('aes-256-gcm',this.key,iv);d.setAAD(Buffer.from('enterprise-lookup'));d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(b),d.final()]).toString())}catch{throw fail('企业查询密钥无法读取，请重新配置','ENTERPRISE_LOOKUP_CONFIG_UNREADABLE',503)}}
  status(id){this.account(id,true);const r=this.db.read(s=>s.enterpriseLookup||{});return {revision:r.revision||0,enabled:r.enabled===true,configured:!!r.credentials,provider:'qcc-735',providerLabel:'企查查 · 企业工商详情（735）',dailyLimit:r.dailyLimit||100,usedToday:r.day===new Date().toISOString().slice(0,10)?r.used||0:0,updatedAt:r.updatedAt||null}}
  async save(id,input,meta={}){this.account(id,true);if(!input||Object.keys(input).some(k=>!['revision','enabled','appKey','secretKey','clearCredentials','dailyLimit','licensed'].includes(k)))throw fail('配置字段无效');if(!Number.isInteger(input.revision)||typeof input.enabled!=='boolean'||!Number.isInteger(input.dailyLimit)||input.dailyLimit<1||input.dailyLimit>10000)throw fail('请设置有效版本、启用状态和每日1–10000次查询上限');if(input.enabled&&input.licensed!==true)throw fail('启用前须确认已获得接口授权并了解计费规则');await this.db.transaction(s=>{this.account(id,true,s);const r=s.enterpriseLookup||{};if((r.revision||0)!==input.revision)throw fail('配置已更新，请刷新后重试','REVISION_CONFLICT',409);let credentials=input.clearCredentials?'':r.credentials||'';const key=clean(input.appKey,128),secret=clean(input.secretKey,128);if(key||secret){if(!/^[A-Za-z0-9_-]{8,128}$/.test(key)||!/^[A-Za-z0-9_-]{8,128}$/.test(secret))throw fail('同时填写有效的 AppKey 和 SecretKey');credentials=this.seal({appKey:key,secretKey:secret})}if(input.enabled&&!credentials)throw fail('尚未配置有效密钥');s.enterpriseLookup={...r,enabled:input.enabled,credentials,dailyLimit:input.dailyLimit,revision:(r.revision||0)+1,updatedAt:new Date().toISOString()};s.auditLogs.unshift(auditRecord('enterprise_lookup.configured','enterprise-lookup',{...meta,actor:id},{enabled:input.enabled,dailyLimit:input.dailyLimit,credentialsChanged:!!(key||input.clearCredentials)}))});this.cache.clear();return this.status(id)}
  region(raw){const catalog=this.regions.current(),items=catalog.items;let row=items.find(r=>r.code==='CN-'+clean(raw.AreaCode,12)&&catalog.active(r.code));const city=clean(raw.Area?.City,80),province=clean(raw.Area?.Province,80);if(!row&&city){const found=items.filter(r=>r.level==='city'&&catalog.active(r.code)&&r.name===city&&(!province||items.some(p=>p.code===r.parentCode&&p.name===province)));if(found.length===1)row=found[0]}if(!row)return {city:'',regionCode:''};const info=this.regions.describe(row.code);return {city:info?.city||city||row.name,regionCode:row.code}}
  normalize(raw,name){if(!raw||canonical(raw.Name)!==canonical(name))return {available:false,reason:'未找到完全匹配的企业全称，请核对营业执照后手动填写',source:'企查查'};const credit=clean(raw.CreditCode,40).toUpperCase();return {available:true,source:'企查查 · 企业工商详情',queriedAt:new Date().toISOString(),enterpriseName:clean(raw.Name,120),fields:{creditCode:/^[0-9ABCDEFGHJKLMNPQRTUWXY]{18}$/.test(credit)?credit:'',industry:clean(raw.Industry?.SmallCategory||raw.Industry?.SubIndustry||raw.Industry?.Industry,60),...this.region(raw),summary:clean(raw.Scope,1200),contactMethod:clean(raw.ContactInfo?.Email||raw.ContactInfo?.PhoneNumber,120)},registration:{address:clean(raw.Address,500),status:clean(raw.Status,80),updatedAt:clean(raw.UpdatedDate,50)},notice:'登记资料仅作填写参考，不代表企业认证通过；请核对并补充真实联系人和证明材料。'}}
  async lookup(id,name,meta={}){this.account(id);name=clean(name,121);if(name.length<4||name.length>120)throw fail('请输入4–120字的营业执照企业全称');const row=this.db.read(s=>s.enterpriseLookup||{});if(!row.enabled||!row.credentials)return {available:false,reason:'企业资料查询服务尚未开通，请先手动填写；管理员可在后台配置授权接口'};const key=row.revision+':'+canonical(name),hit=this.cache.get(key);if(hit&&hit.expires>Date.now())return structuredClone(hit.value);let work=this.pending.get(key);if(!work){work=this.query(id,name,row,meta).finally(()=>this.pending.delete(key));this.pending.set(key,work)}const result=await work;this.account(id);if(this.db.read(s=>s.enterpriseLookup?.revision)!==row.revision)throw fail('查询配置已变更，请重试','REVISION_CONFLICT',409);return structuredClone(result)}
  async query(id,name,row,meta){await this.db.transaction(s=>{this.account(id,false,s);const r=s.enterpriseLookup;if(!r?.enabled||r.revision!==row.revision)throw fail('查询服务配置已变更','REVISION_CONFLICT',409);const day=new Date().toISOString().slice(0,10);if(r.day!==day){r.day=day;r.used=0}if((r.used||0)>=r.dailyLimit)throw fail('今日企业资料查询额度已用完，请手动填写','ENTERPRISE_LOOKUP_QUOTA',429);r.used=(r.used||0)+1;s.auditLogs.unshift(auditRecord('enterprise_lookup.queried','enterprise-lookup',{...meta,actor:id},{provider:'qcc-735'}))});const {appKey,secretKey}=this.secrets(row),time=String(Math.floor(Date.now()/1000)),url=new URL(endpoint);url.searchParams.set('key',appKey);url.searchParams.set('searchKey',name);let response;try{response=await this.fetcher(url,{redirect:'error',signal:AbortSignal.timeout(8000),headers:{Accept:'application/json',Timespan:time,Token:createHash('md5').update(appKey+time+secretKey).digest('hex').toUpperCase()}});if(!response.ok||Number(response.headers.get('content-length')||0)>2*1024*1024)throw Error();const reader=response.body.getReader();let bytes=0,chunks=[];try{for(;;){const{done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>2*1024*1024)throw Error();chunks.push(Buffer.from(value))}}finally{await reader.cancel().catch(()=>{})}const payload=JSON.parse(Buffer.concat(chunks).toString());if(String(payload.Status)!=='200')return {available:false,reason:'查询服务未返回可用结果，请检查名称或手动补充；管理员可检查接口额度和授权'};const result=this.normalize(payload.Result,name);if(this.cache.size>=300)this.cache.delete(this.cache.keys().next().value);this.cache.set(row.revision+':'+canonical(name),{expires:Date.now()+12*60*60*1000,value:result});return result}catch{throw fail('企业查询服务暂不可用，已填写内容不会丢失，请手动补充','ENTERPRISE_LOOKUP_UNAVAILABLE',503)}}
}
