<script setup>
import { ref,computed,onMounted,onBeforeUnmount,watch } from 'vue'
import PageHeader from '../components/PageHeader.vue'
import { api } from '../lib/api.js'
const items=ref([]),query=ref(''),error=ref(''),notice=ref(''),loading=ref(false),saving=ref(false)
const form=ref(null),preview=ref(''),fileInput=ref(null)
const visible=computed(()=>items.value.filter(s=>[s.name,s.category].some(x=>x.includes(query.value.trim()))))
const asset=s=>new URL(s.url,new URL(import.meta.env.VITE_API_BASE_URL||'/api/v1',location.origin)).href
async function load(){loading.value=true;try{items.value=(await api('/admin/chat-stickers')).items;error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
function edit(s){form.value=s?{id:s.id,name:s.name,category:s.category,sortOrder:s.sortOrder,status:s.status}:{name:'',category:'常用',sortOrder:0,status:'active'};preview.value=s?.status==='active'?asset(s):'';error.value='';notice.value=''}
function fileChanged(e){const file=e.target.files[0];if(!file)return;if(file.size>500*1024*1024){error.value='单张表情图片不能超过500MB';return}if(!['image/png','image/jpeg','image/gif','image/webp'].includes(file.type)){error.value='请选择PNG、JPG、GIF或WebP';return}preview.value=URL.createObjectURL(file);form.value.fileSource=file;form.value.filename=file.name;form.value.mimeType=file.type}
watch(preview,(_next,previous)=>{if(previous?.startsWith('blob:'))URL.revokeObjectURL(previous)})
onBeforeUnmount(()=>{if(preview.value.startsWith('blob:'))URL.revokeObjectURL(preview.value)})
async function save(){if(saving.value)return;saving.value=true;error.value='';try{const {id,...body}=form.value;await api('/admin/chat-stickers'+(id?'/'+id:''),{method:id?'PUT':'POST',body});form.value=null;notice.value='表情素材已保存，用户重新打开表情面板后可见';await load()}catch(e){error.value=e.message}finally{saving.value=false}}
onMounted(load)
</script>
<template><div><PageHeader title="聊天表情包" description="管理聊天中的表情分类与图片，支持 PNG、JPG、GIF、WebP；每张不超过500MB。"/><div class="sticker-toolbar"><input v-model="query" placeholder="搜索名称或分类"/><button class="button button-primary" @click="edit()">新增表情</button><button class="button button-secondary" @click="load">刷新</button></div><p v-if="error" role="alert" class="sticker-error">{{ error }}</p><p v-if="notice" role="status" class="sticker-success">{{ notice }}</p><p v-if="loading">正在读取…</p><div class="sticker-cards"><article v-for="s in visible" :key="s.id"><img v-if="s.status==='active'" :src="asset(s)" :alt="s.name"/><div v-else class="sticker-hidden">已下架</div><h3>{{ s.name }}</h3><p>{{ s.category }} · 排序 {{ s.sortOrder }}</p><p>{{ s.status==='active'?'已上架':'已下架' }}</p><button class="button button-secondary" @click="edit(s)">编辑 / 调整状态</button></article></div><div v-if="!items.length&&!loading" class="sticker-empty">尚未配置表情包，点击“新增表情”上传素材。</div><div v-if="form" class="sticker-overlay"><form class="sticker-editor" @submit.prevent="save"><h2>{{ form.id?'编辑表情':'新增表情' }}</h2><label>名称<input v-model.trim="form.name" required maxlength="40"/></label><label>分类<input v-model.trim="form.category" required maxlength="40" list="sticker-categories"/><datalist id="sticker-categories"><option v-for="c in [...new Set(items.map(s=>s.category))]" :key="c" :value="c"/></datalist></label><label>排序（数字越小越靠前）<input type="number" v-model.number="form.sortOrder" min="-10000" max="10000" required/></label><label>状态<select v-model="form.status"><option value="active">上架</option><option value="hidden">下架</option></select></label><label>图片（编辑时不选则保留原图）<input ref="fileInput" type="file" accept="image/png,image/jpeg,image/gif,image/webp" @change="fileChanged"/></label><img v-if="preview" :src="preview" class="sticker-preview" alt="表情预览"/><p v-if="error" class="sticker-error">{{ error }}</p><div class="sticker-actions"><button class="button button-secondary" type="button" :disabled="saving" @click="form=null">取消</button><button class="button button-primary" :disabled="saving">{{ saving?'保存中…':'保存' }}</button></div></form></div></div></template>
<style scoped>
.sticker-toolbar{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.sticker-toolbar input{min-width:220px;flex:1}.sticker-toolbar input,.sticker-editor input,.sticker-editor select{border:1px solid #dce4ef;border-radius:9px;padding:11px;font:inherit;min-width:0}.sticker-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:18px}.sticker-cards article{background:white;border:1px solid #e1e8f2;border-radius:16px;padding:20px;font-size:14px}.sticker-cards img,.sticker-hidden{height:120px;width:100%;object-fit:contain}.sticker-hidden{display:grid;place-items:center;background:#f0f3f8;border-radius:10px;color:#8590a0}.sticker-cards h3{font-size:17px;overflow-wrap:anywhere}.sticker-cards p{color:#758398}.sticker-error{color:#ac3d35}.sticker-success{color:#176551}.sticker-empty{padding:40px;background:white;border-radius:16px;text-align:center;color:#7b889b}.sticker-overlay{position:fixed;inset:0;background:#10213a66;z-index:100;display:flex;justify-content:center;align-items:center;padding:20px}.sticker-editor{max-width:560px;width:100%;max-height:90vh;overflow:auto;background:white;border-radius:20px;padding:28px}.sticker-editor label{display:flex;flex-direction:column;gap:8px;margin:16px 0;font-size:14px}.sticker-preview{display:block;width:120px;height:120px;object-fit:contain}.sticker-actions{display:flex;gap:12px;justify-content:flex-end;margin-top:20px}
</style>
