<script setup>
import {onMounted,ref} from 'vue'
import {api,accessToken} from '../lib/api.js'
const state=ref(null),error=ref(''),success=ref(''),busy=ref(false),appKey=ref(''),secretKey=ref(''),licensed=ref(false),clearCredentials=ref(false)
async function load(){const token=accessToken();try{const result=await api('/admin/enterprise-lookup');if(accessToken()===token){state.value=result;error.value=''}}catch(e){if(accessToken()===token)error.value=e.message}}
async function save(){if(busy.value||!state.value)return;const token=accessToken();busy.value=true;error.value='';success.value='';try{const result=await api('/admin/enterprise-lookup',{method:'PUT',body:{revision:state.value.revision,enabled:state.value.enabled,dailyLimit:Number(state.value.dailyLimit),appKey:appKey.value,secretKey:secretKey.value,licensed:licensed.value,clearCredentials:clearCredentials.value}});if(accessToken()!==token)return;state.value=result;appKey.value='';secretKey.value='';clearCredentials.value=false;success.value='配置已保存。前台仅回填来源可用的资料，仍需企业认证审核。'}catch(e){if(accessToken()===token){error.value=e.message;if(e.status===409)await load()}}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="lookup-page"><header><p>湖财人管理后台</p><h1>企业资料自动补全</h1><p>为企业认证申请提供工商资料查询。不会自动通过认证，也不会推断申请人与企业的关系。</p></header><p v-if="error" class="lookup-error" role="alert">{{error}}</p><p v-if="success" class="lookup-success" role="status">{{success}}</p><form v-if="state" class="lookup-form" @submit.prevent="save"><h2>{{state.providerLabel}}</h2><p>管理员需要自行开通并获得应用场景授权。查询可能按服务商规则计费，平台没有内置商业接口密钥。</p><a href="https://openapi.qcc.com/dataApi/735" target="_blank" rel="noopener noreferrer">查看服务商接口与计费说明 ↗</a><label class="lookup-check"><input v-model="state.enabled" type="checkbox">启用企业名称自动查询</label><label>每日查询上限<input v-model="state.dailyLimit" type="number" min="1" max="10000" required></label><p>今日已请求 {{state.usedToday}} 次（按 UTC 日期计数）；同一企业成功结果缓存 12 小时。失败请求也可能被服务商计费。</p><label>AppKey<input v-model.trim="appKey" type="password" maxlength="128" autocomplete="new-password" :placeholder="state.configured?'已配置；留空保留，仅替换时填写':'请输入服务商 AppKey'"></label><label>SecretKey<input v-model.trim="secretKey" type="password" maxlength="128" autocomplete="new-password" :placeholder="state.configured?'已加密保存；不会回显':'请输入服务商 SecretKey'"></label><label class="lookup-check"><input v-model="licensed" type="checkbox">我已取得接口授权，并了解查询可能产生费用</label><label class="lookup-check"><input v-model="clearCredentials" type="checkbox">清除已保存密钥（需先关闭查询）</label><button type="submit" :disabled="busy">{{busy?'保存中…':'保存配置'}}</button></form><button v-else @click="load">重新加载配置</button></div></template>
<style scoped>
.lookup-page{max-width:1000px;margin:auto;overflow-wrap:anywhere}.lookup-page header>p:first-child{color:#9a7b48}.lookup-page h1{margin:8px 0}.lookup-page p{color:#627590;line-height:1.7}.lookup-form{display:grid;gap:18px;padding:28px;background:#fff;border:1px solid #d4dfef;border-radius:20px;margin-top:24px}.lookup-form label{display:grid;gap:9px;color:#223955;font-weight:600}.lookup-form input:not([type=checkbox]){box-sizing:border-box;width:100%;min-width:0;padding:12px;border:1px solid #c5d3e7;border-radius:9px;font:inherit}.lookup-form label.lookup-check{display:flex;align-items:flex-start;font-weight:400}.lookup-form button,.lookup-page>button{padding:14px;border:0;border-radius:10px;background:#0b3b83;color:#fff;font:inherit;cursor:pointer}.lookup-error{color:#9b302d!important}.lookup-success{color:#21644f!important}@media(max-width:600px){.lookup-form{padding:18px}}
</style>
