<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue'
import { api, accessToken } from '../lib/api.js'
import { formatDateTime } from '../lib/format.js'
import { loadAllPages } from '../../../utils/pagination.js'
import PageHeader from '../components/PageHeader.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'

const role=ref(null),staff=ref([]),stations=ref([]),records=ref([]),people=ref([]),query=ref(''),page=ref(1),total=ref(0),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),action=ref(null),stationForm=ref({name:'',description:''})
let generation=0,ownerToken='',alive=true,timer
function clearSensitive(){role.value=null;staff.value=[];stations.value=[];records.value=[];people.value=[];action.value=null;stationForm.value={name:'',description:''};total.value=0}
function current(g,token){if(token!==accessToken()){generation++;clearSensitive();return false}return alive&&g===generation&&token===ownerToken}
function fail(e){error.value=e.message||'操作失败';if([401,403].includes(e.status))clearSensitive()}
async function load(){const g=++generation,token=accessToken();if(ownerToken!==token)clearSensitive();ownerToken=token;loading.value=true;error.value='';try{const me=await api('/gate/me',{token});if(!current(g,token))return;role.value=me;if(!me.canManage){clearSensitive();error.value='当前账号没有核验管理权限';return}const [s,t]=await Promise.all([loadAllPages(params=>api('/gate/staff?'+new URLSearchParams(params),{token}),{},()=>current(g,token)&&role.value?.canManage),api('/gate/stations?includeInactive=true',{token})]);if(!current(g,token))return;staff.value=s.items||[];stations.value=t.items||[];await loadRecords()}catch(e){if(current(g,token))fail(e)}finally{if(current(g,token))loading.value=false}}
async function checkRole(){const g=generation,token=ownerToken;if(!alive||!token||busy.value||loading.value)return;try{const me=await api('/gate/me',{token});if(!current(g,token))return;if(!me.canManage){clearSensitive();error.value='核验管理权限已被撤销';return}role.value=me}catch(e){if(current(g,token))fail(e)}}
async function loadRecords(){if(!role.value?.canManage)return;const g=generation,token=ownerToken,p=page.value;try{const result=await api('/gate/records?'+new URLSearchParams({page:p,pageSize:20}),{token});if(current(g,token)&&p===page.value){records.value=result.items||[];total.value=result.total||0}}catch(e){if(current(g,token))fail(e)}}
async function searchPeople(){if(!role.value?.canManage||busy.value)return;const q=query.value.trim();people.value=[];if(!q)return;const g=generation,token=ownerToken;busy.value=true;error.value='';try{const result=await loadAllPages(params=>api('/gate/people?'+new URLSearchParams(params),{token}),{query:q},()=>current(g,token)&&role.value?.canManage&&q===query.value.trim());if(current(g,token)&&q===query.value.trim())people.value=result.items||[]}catch(e){if(current(g,token))fail(e)}finally{if(current(g,token))busy.value=false}}
function prepare(title,description,path,method,body){if(!role.value?.canManage||busy.value||!current(generation,ownerToken))return;action.value={title,description,path,method,body,g:generation,token:ownerToken}}
function grant(person,value){if(value==='manager'&&!role.value?.canGrantManagers)return;prepare('确认分配核验权限',`将 ${person.name||person.realName||person.username}（${person.username}）设为${value==='manager'?'保卫负责人':'保安'}。保安使用前台平台账号登录，不需要分配后台管理员权限。`,'/gate/staff','POST',{accountId:person.id,role:value})}
function revoke(person){if(!person.canRevoke||person.status!=='active')return;prepare('撤销核验工作权限',`撤销 ${person.person?.name||person.person?.username} 的${person.role==='manager'?'保卫负责人':'保安'}权限，历史核验记录保留。`,'/gate/staff/'+person.id,'DELETE')}
function editStation(row){action.value=null;stationForm.value=row?{id:row.id,name:row.name,description:row.description||'',expectedRevision:row.revision}:{name:'',description:''}}
function saveStation(){const form=stationForm.value;if(!form.name.trim())return;prepare(form.id?'修改核验站点':'新增核验站点',`保存核验站点“${form.name.trim()}”？`,'/gate/stations'+(form.id?'/'+form.id:''),form.id?'PATCH':'POST',{name:form.name.trim(),description:form.description.trim(),...(form.id?{expectedRevision:form.expectedRevision}:{})})}
function toggleStation(row){const status=row.status==='active'?'disabled':'active';prepare(status==='active'?'启用核验站点':'停用核验站点',`${status==='active'?'启用':'停用'}“${row.name}”。停用站点不能继续核验；历史记录保留。`,'/gate/stations/'+row.id,'PATCH',{status,expectedRevision:row.revision})}
async function apply(){const item=action.value;if(!item||busy.value||!role.value?.canManage||(item.body?.role==='manager'&&!role.value.canGrantManagers)||!current(item.g,item.token))return;busy.value=true;error.value='';notice.value='';try{await api(item.path,{method:item.method,body:item.body,token:item.token});if(!current(item.g,item.token))return;action.value=null;people.value=[];stationForm.value={name:'',description:''};notice.value='核验配置已保存';await load()}catch(e){if(current(item.g,item.token)){action.value=null;fail(e);if(e.status===409){await load();error.value='配置已被其他管理员更新，请基于最新内容重新确认'}}}finally{if(alive&&item.token===accessToken())busy.value=false}}
onMounted(()=>{load();timer=setInterval(checkRole,15000)})
onBeforeUnmount(()=>{alive=false;generation++;clearInterval(timer);clearSensitive()})
</script>

<template>
  <div><PageHeader title="平台返校身份核验" description="授权核验人员、维护核验站点，并查看明确确认后的放行与拒绝记录。"><template #actions><button class="button button-secondary" :disabled="loading||busy" @click="load">刷新</button></template></PageHeader>
    <p v-if="error" class="gate-error" role="alert">{{ error }}</p><p v-if="notice" class="gate-success" role="status">{{ notice }}</p><p v-if="loading">正在读取核验配置…</p>
    <template v-if="role?.canManage">
      <section class="gate-info"><strong>核验工作流程</strong><p>正式实名用户在“我的湖财身份卡”出示每5秒自动更新的动态码 → 授权保安在前台“我的 / 返校身份核验工作台”扫码 → 现场核对本人 → 填写说明并明确确认放行或拒绝。仅扫描不构成放行。</p><p>保卫负责人可以给已有普通人员账号分配保安权限。需要新账号时，请先在账号管理中的人员管理创建；这里不会授予系统后台管理员权限。</p></section>
      <div class="gate-grid"><section class="gate-box"><h2>授权核验人员</h2><div class="gate-search"><input v-model="query" placeholder="搜索现有姓名或平台用户名" maxlength="60" @keydown.enter="searchPeople"/><button class="button button-primary" :disabled="busy" @click="searchPeople">搜索</button></div><div v-for="person in people" :key="person.id" class="gate-row"><div><strong>{{ person.name||person.realName }} · {{ person.username }}</strong><small>{{ person.department }}</small></div><div class="gate-actions"><button v-if="role.canGrantManagers" :disabled="busy" @click="grant(person,'manager')">设为负责人</button><button :disabled="busy" @click="grant(person,'guard')">设为保安</button></div></div><h3>已授权人员</h3><div v-for="person in staff" :key="person.id" class="gate-row"><div><strong>{{ person.person?.name||person.person?.username }}</strong><small>{{ person.person?.username }} · {{ person.role==='manager'?'保卫负责人':'保安' }} · {{ person.status==='active'&&person.effective?'权限有效':'已失效' }}</small><small v-if="person.assignedByName">授权人：{{ person.assignedByName }}</small></div><button v-if="person.canRevoke&&person.status==='active'" :disabled="busy" @click="revoke(person)">撤销权限</button></div><p v-if="!staff.length">暂无授权人员。</p></section>
        <section class="gate-box"><h2>核验站点</h2><form @submit.prevent="saveStation"><h3>{{ stationForm.id?'编辑站点':'新增站点' }}</h3><label>站点名称<input v-model="stationForm.name" required maxlength="80" placeholder="例如：返校接待核验点" :disabled="busy"/></label><label>说明<textarea v-model="stationForm.description" maxlength="300" rows="2" :disabled="busy"/></label><div class="gate-actions"><button type="submit" class="button button-primary" :disabled="busy||!stationForm.name.trim()">预览并保存</button><button v-if="stationForm.id" type="button" class="button button-secondary" :disabled="busy" @click="editStation(null)">取消编辑</button></div></form><div v-for="station in stations" :key="station.id" class="gate-row"><div><strong>{{ station.name }}</strong><small>{{ station.status==='active'?'启用中':'已停用' }} · 版本 {{ station.revision }}</small><small>{{ station.description }}</small></div><div class="gate-actions"><button :disabled="busy" @click="editStation(station)">编辑</button><button :disabled="busy" @click="toggleStation(station)">{{ station.status==='active'?'停用':'启用' }}</button></div></div><p v-if="!stations.length">暂无核验站点，请先新增。</p></section>
      </div>
      <section class="gate-box"><div class="gate-section-head"><h2>已确认核验记录</h2><button class="button button-secondary" :disabled="busy" @click="loadRecords">刷新记录</button></div><p>共 {{ total }} 条。扫码预览不产生放行记录；每条记录保留办理人员与确认说明。</p><div class="gate-table-wrap"><table><thead><tr><th>时间</th><th>待核验人员</th><th>站点</th><th>核验人</th><th>结果</th><th>确认说明</th></tr></thead><tbody><tr v-for="row in records" :key="row.id"><td>{{ formatDateTime(row.createdAt) }}</td><td>{{ row.person?.name||row.personName||'—' }}<small>{{ row.person?.department }}</small></td><td>{{ row.station?.name||row.stationName||'—' }}</td><td>{{ row.operator?.name||row.operatorName||'—' }}</td><td><span :class="row.decision==='allow'?'gate-allowed':'gate-denied'">{{ row.decision==='allow'?'确认放行':'不予放行' }}</span></td><td>{{ row.reason }}</td></tr><tr v-if="!records.length"><td colspan="6">暂无已确认记录</td></tr></tbody></table></div><footer class="gate-pagination"><button :disabled="page<=1||busy" @click="page--;loadRecords()">上一页</button><span>{{ page }} / {{ Math.max(1,Math.ceil(total/20)) }}</span><button :disabled="page*20>=total||busy" @click="page++;loadRecords()">下一页</button></footer></section>
    </template>
    <ConfirmDialog :open="!!action" :title="action?.title||'确认核验配置'" :description="action?.description||''" confirm-text="确认保存" :busy="busy" :confirm-disabled="!role?.canManage" @confirm="apply" @cancel="action=null"/>
  </div>
</template>

<style scoped>
.gate-info,.gate-box{padding:24px;background:white;border:1px solid #dce5ef;border-radius:16px;margin:20px 0;min-width:0}.gate-info{background:#eef5ff}.gate-info p,.gate-box p{font-size:14px;color:#6f8199;line-height:1.8;margin:10px 0}.gate-info strong{color:#264f7a}.gate-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:22px}.gate-grid>.gate-box{margin-top:0}.gate-box h2{font-size:20px;margin:0 0 20px}.gate-box h3{font-size:16px;color:#3c5574;margin:24px 0 12px}.gate-box label{display:block;margin:14px 0;font-size:14px}.gate-box input,.gate-box textarea{box-sizing:border-box;width:100%;min-width:0;padding:11px;border:1px solid #d9e3ee;border-radius:9px;font:inherit;font-size:14px;margin-top:8px}.gate-box textarea{resize:vertical}.gate-search,.gate-actions,.gate-section-head,.gate-pagination{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.gate-search input{flex:1;margin:0}.gate-row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:17px 0;border-bottom:1px solid #e8eef5;font-size:14px}.gate-row>div:first-child{flex:1;min-width:0;overflow-wrap:anywhere}.gate-row small,.gate-box td small{display:block;margin-top:5px;color:#7b8c9f;line-height:1.6}.gate-box button:not(.button){padding:8px 12px;border:1px solid #dce4ef;border-radius:8px;color:#285887;background:#f1f6fc;font-size:14px;cursor:pointer}.gate-box button:disabled{opacity:.5;cursor:default}.gate-section-head{justify-content:space-between}.gate-section-head h2{margin:0}.gate-table-wrap{overflow-x:auto;margin-top:20px}.gate-box table{width:100%;min-width:740px;border-collapse:collapse;font-size:14px}.gate-box th,.gate-box td{text-align:left;padding:14px 12px;border-bottom:1px solid #e7eef6;line-height:1.7;max-width:300px;overflow-wrap:anywhere;vertical-align:top}.gate-box th{background:#f3f7fc;color:#667d99}.gate-pagination{justify-content:flex-end;margin-top:20px;font-size:14px}.gate-error{color:#b33c3c}.gate-success,.gate-allowed{color:#26734d}.gate-denied{color:#a64338}@media(max-width:1150px){.gate-grid{grid-template-columns:1fr;gap:0}}@media(max-width:600px){.gate-row{align-items:flex-start;flex-direction:column}.gate-box,.gate-info{padding:18px}}
</style>
