<script setup>
import { ref,computed,onMounted } from 'vue'
import { api } from '../lib/api.js'
import PageHeader from '../components/PageHeader.vue'
const items=ref([]),query=ref(''),input=ref(''),enabled=ref(true),error=ref(''),notice=ref(''),loading=ref(false),saving=ref(false),page=ref(1)
const filtered=computed(()=>items.value.filter(w=>w.word.includes(query.value.trim()))),visible=computed(()=>filtered.value.slice((page.value-1)*30,page.value*30))
async function load(){loading.value=true;try{items.value=(await api('/admin/sensitive-words')).items;page.value=Math.max(1,Math.min(page.value,Math.ceil(filtered.value.length/30)));error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
async function add(){if(saving.value)return;saving.value=true;error.value='';notice.value='';try{const words=input.value.split(/\r?\n/).map(w=>w.trim()).filter(Boolean);const r=await api('/admin/sensitive-words',{method:'POST',body:{words,enabled:enabled.value}});notice.value=`新增 ${r.added} 条，更新 ${r.updated} 条，已立即生效`;input.value='';await load()}catch(e){error.value=e.message}finally{saving.value=false}}
async function toggle(w){if(saving.value)return;saving.value=true;try{await api('/admin/sensitive-words/'+w.id,{method:'PATCH',body:{enabled:!w.enabled}});await load()}catch(e){error.value=e.message}finally{saving.value=false}}
async function importFile(e){const file=e.target.files[0];if(!file)return;if(file.size>100000){error.value='词库文件请控制在100KB以内';return}input.value=await file.text();e.target.value=''}
onMounted(load)
</script>
<template><div><PageHeader title="敏感词库" description="命中已启用词条的前台文本将被服务端拒绝提交，覆盖发帖、评论、留言、群名称及对话消息。"/><div class="word-layout"><section class="word-panel"><h2>新增 / 批量导入</h2><p>每行一个词条，每次最多500条。重复词条更新启用状态，不重复创建。</p><textarea v-model="input" placeholder="输入限制用语，每行一个" rows="9" maxlength="31000"/><label class="word-file">从 TXT 文件导入<input type="file" accept=".txt,text/plain" @change="importFile"/></label><label class="word-check"><input type="checkbox" v-model="enabled"/>保存后立即启用</label><button class="button button-primary" :disabled="saving||!input.trim()" @click="add">{{ saving?'保存中…':'保存词条' }}</button><p v-if="notice" role="status" class="word-success">{{ notice }}</p><p class="word-hint">匹配时忽略大小写、全半角、空格和不可见分隔符。不使用正则表达式；仅检查提交的文本，不识别图片或文件内的文字。</p></section><section class="word-panel"><div class="word-head"><h2>词条列表（{{ items.length }}）</h2><button class="button button-secondary" @click="load">刷新</button></div><input class="word-search" v-model="query" @input="page=1" placeholder="搜索词条"/><p v-if="loading">正在读取…</p><div v-for="w in visible" :key="w.id" class="word-row"><strong>{{ w.word }}</strong><span :class="w.enabled?'word-enabled':'word-muted'">{{ w.enabled?'已启用':'已停用' }}</span><button class="button button-secondary" :disabled="saving" @click="toggle(w)">{{ w.enabled?'停用':'启用' }}</button></div><p v-if="!filtered.length&&!loading" class="word-hint">{{ items.length?'没有匹配词条':'词库为空；添加并启用后开始拦截。' }}</p><div class="word-pager"><button class="button button-secondary" :disabled="page<=1" @click="page--">上一页</button><span>{{ page }} / {{ Math.max(1,Math.ceil(filtered.length/30)) }}</span><button class="button button-secondary" :disabled="page*30>=filtered.length" @click="page++">下一页</button></div></section></div><p v-if="error" class="word-error" role="alert">{{ error }}</p></div></template>
<style scoped>
.word-layout{display:grid;grid-template-columns:minmax(280px,.7fr) minmax(0,1.3fr);gap:24px;margin-top:24px}.word-panel{min-width:0;background:white;border:1px solid #e1e7f0;border-radius:18px;padding:24px}.word-panel h2{font-size:19px;margin:0 0 16px}.word-panel p{font-size:14px;line-height:1.7;color:#7a8799}.word-panel textarea,.word-search{width:100%;border:1px solid #dce4ef;border-radius:10px;padding:12px;font:inherit;box-sizing:border-box}.word-file{display:block;font-size:14px;margin:16px 0}.word-file input{display:block;max-width:100%;margin-top:8px}.word-check{display:flex;align-items:center;gap:8px;margin:20px 0;font-size:14px}.word-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}.word-head h2{margin:0}.word-row{display:flex;align-items:center;gap:14px;padding:14px 0;border-bottom:1px solid #edf0f5;font-size:14px}.word-row strong{min-width:0;flex:1;overflow-wrap:anywhere}.word-enabled{color:#176551}.word-muted{color:#8b98ac}.word-pager{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:20px;font-size:14px}.word-error{color:#a23d35}.word-panel .word-success{color:#176551}@media(max-width:1050px){.word-layout{grid-template-columns:1fr}}
</style>
